stages:
  - build

build-backend-rust-latest:
  stage: build
  image: rust:latest
  script:
    - cd backend
    - head -c16 /dev/urandom > jwt_secret.key   # This is here so compilation can proceed
    - rustc --version
    - cargo --version
    - cargo test
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup component add clippy
    - cargo clippy -- -D warnings
    - cargo install cargo-audit
    - cargo audit

build-backend-rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cd backend
    - head -c16 /dev/urandom > jwt_secret.key   # This is here so compilation can proceed
    - rustc --version
    - cargo --version
    - cargo test
    - rustup component add rustfmt
    - cargo fmt -- --check
    - rustup component add clippy
    - cargo clippy -- -D warnings
    - cargo install cargo-audit
    - cargo audit
  allow_failure: true