-- Your SQL goes here
CREATE TABLE IF NOT EXISTS Users ( id SERIAL PRIMARY KEY, username VARCHAR(24));
CREATE TABLE IF NOT EXISTS Communities ( id SERIAL PRIMARY KEY, uuid VARCHAR(100) NOT NULL, title VARCHAR(100) NOT NULL);
CREATE TABLE IF NOT EXISTS Posts ( id SERIAL PRIMARY KEY, uuid VARCHAR(100) NOT NULL, title VARCHAR(100) NOT NULL);
